config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"
  resources :offers, only: [:new, :create, :show] do
    resources :bookings, only: [:new, :create, :show, :destroy]
  end
  resources :bookings, only: [:index]
  resources :offers, only: [:destroy]
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  validates :booked_on, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :photos, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: { in: 20..500 }
  validates :localisation, presence: true
  validates :price, presence: true, comparison: { greater_than: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :offers, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  has_many :requests, through: :offers, source: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :age, presence: true, comparison: { greater_than_or_equal_to: 18 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :age, :hair_color, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :gender, :age, :hair_color, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @requests = current_user.requests
    @bookings = current_user.bookings
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @user = @offer.user
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = Offer.find(params[:offer_id])
    if @booking.save
      redirect_to offer_path(Offer.find(params[:offer_id]))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :offer_id, :booked_on, :message)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @offers = Offer.with_attached_photos.all
  end

  def new
    @offer = Offer.new
    @user = current_user
  end

  def create
    @offer = Offer.new(offer_params)
    @user = current_user
    @offer.user = @user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @offer = Offer.with_attached_photos.find(params[:id])
    @user = @offer.user
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(:user_id, :title, :description, :localisation, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @offers = Offer.with_attached_photos.where(user: @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_footer.html.erb
<div class="footer-dark">
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-3 item">
          <%= image_tag "logo", alt: "logo_date_faker", width: "auto", height: "120" %>
        </div>
        <div class="col-sm-6 col-md-3 item">
          <ul>
            <a href="#"><h3>A propos</h3></a>
            <a href="#"><h3>Réserver un fake date</h3></a>
            <a href="#"><h3>Offrir un service</h3></a>
            <a href="#"><h3>Carrière</h3></a>
          </ul>
        </div>
        <div class="col-md-6 item text">
            <h3>Date Faker</h3>
            <p>Amour sans détour! <br> Trouve ton fake date pour tous les évènements en 1 clic</p>
        </div>
        <div class="col item social">
          <a href="#"><i class="fa-brands fa-facebook fa-xl icon ion-social-facebook"></i></a>
          <a href="#"><i class="icon ion-social-twitter fa-brands fa-instagram fa-xl"></i></a>
          <a href="#"><i class="icon ion-social-snapchat fa-brands fa-github fa-xl"></i></a>
          <a href="#"><i class="icon ion-social-instagram fa-solid fa-poo fa-xl"></i></a>
        </div>
      </div>
    </div>
    <p class="copyright">Date Faker © 2024</p>
  </footer>
</div>

app/views/bookings/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-offer">
    <% if !user_signed_in? %>
      <%= link_to(new_user_session_path) do %>
        <i class="fa-regular fa-user avatar"></i>
      <% end %>
    <% elsif current_user.photo.key.nil? %>
      <%= link_to(user_path(current_user)) do%>
        <i class="fa-regular fa-user avatar"></i>
      <% end %>
    <% else %>
      <%= link_to(user_path(current_user)) do%>
        <%= cl_image_tag current_user.photo.key, crop: :fill, alt: "user avatar", class: "avatar" %>
      <% end %>
    <% end %>

    <% if user_signed_in? %>
      <div class="navbar-offer">
        <%= button_to destroy_user_session_path, method: :delete do %>
          <i class="fa-solid fa-right-from-bracket"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= link_to(root_path) do %>
    <div class="navbar-logo" style="display: flex; align-items: center;">
      <%= image_tag "logo", alt: "logo", style: "margin-right: 10px;" %>
      <div class="text-logo">
        <p style="margin: 0">Date Faker</p>
      </div>
    </div>
  <% end %>

  <div class="navbar-offers">
    <div class="navbar-offer">
      <%= link_to "Je dépose une offre", new_offer_path, class: "offer-btn"%>
    </div>
    <div class="navbar-offer">
      <%= link_to "Mes réservations", bookings_path, class: "offer-btn"%>
    </div>
  </div>
</nav>

app/views/bookings/index.html.erb
<%= render "navbar" %>

<!-- Card with dropdown for 'Les gens ont réservé mes offres' -->
<div class="card">
  <details class="dropdown-card" open>
    <summary class="dropdown-title">
      Mes demandes
    </summary>
    <div class="section">
      <% if @requests.any?%>
        <div class="d-flex justify-content-start gap-3">
        <% @requests.each do |booking| %>
            <div>
              <%= cl_image_tag booking.offer.photos.first.key, height: 200, width: 300, crop: :fill  %>
              <p><strong>Nom: </strong><%= booking.offer.user.first_name %> <%= booking.offer.user.last_name %><br>
                <%= booking.message %><br><strong>Date: </strong><%= booking.booked_on %>
              </p>
            </div>
          <% end %>
        </div>
      <% else %>
        <h3>Woah c'est vide!</h3>
      <% end %>
    </div>
  </details>
</div>

<div class="card">
  <details class="dropdown-card" open>
    <summary class="dropdown-title">
      Mes réservations
    </summary>
    <div class="section">
      <% if @bookings.any? %>
        <div class="d-flex justify-content-start gap-3">
          <% @bookings.each do |b| %>
          <div>
            <%= cl_image_tag b.offer.photos.first.key, height: 200, width: 300, crop: :fill  %>
            <p><strong>Nom: </strong><%= b.offer.user.first_name %> <%= b.offer.user.last_name %> <br>
              <strong>Date: </strong><%= b.booked_on %>
            </p>
          </div>
          <% end %>
        </div>
      <% else %>
        <h3>Woah c'est vide!</h3>

      <% end %>
    </div>
  </details>
</div>

<%= render "footer" %>

app/views/bookings/new.html.erb
<%= render "navbar" %>
<div class="container justify-content-center">
  <div class="card-booking-info-left justify-content-center align-items-center mb-3 p-3" style="background-color:#fff">
    <div class="booking-info">
      <h2>Réservation</h2>
      <h3>Envoyez un message avant de réserver votre Date Faker !</h3>
      <p>Indiquez la raison de votre réservation et les détails qui pourraient être interéssants pour votre futur Date Faker.</p>
    </div>
    <div class="card-user-offer">
      <div class="card-user-offer-title">
        <div class="avatar-name d-flex align-items-center justify-content-start">
          <% if !@user.photo.key.nil? %>
            <%= cl_image_tag @user.photo.key, crop: :fill, alt: "#{@user.first_name} photo", class: "avatar" %>
          <% else %>
            <h4 class="avatar-round"><%= @user.first_name.chars[0] %><%= @user.last_name.chars[0] %> </h4>
          <% end %>
          <h3 id="name_avatar"><%= @user.first_name %> <%= @user.last_name %></h3>
        </div>
        <p>Age : <%= @user.age %></p>
        <p>Genre : <%= @user.gender %></p>
        <% if !@user.hair_color=="" %>
          <p>Couleur de cheveux : <%= @user.hair_color %></p>
        <% else %>
          <p>Couleur de cheveux : Non renseigné</p>
        <% end %>
      </div>
    </div>
    <div class="message-booking">
      <%= simple_form_for [@offer, @booking] do |f| %>
        <div class="form-inputs">
          <%= f.input :message, label: false , placeholder: "Envoyer un message...",
                      autofocus: true%>
          <%= f.input :booked_on,
              label: "Date de réservation",
              as: :string,
              autofocus: true,
              input_html: { data: { controller: "datepicker" } } %>

          <%= f.submit%>
        </div>
<% end %>
    </div>
  </div>
  <div class="booking-container">
  <div class="card-booking-info-right d-flex flex-column justify-content-start mb-3 p-3" style="background-color:#fff">
    <section class="booking-info-top d-flex flex-row justify-content-between">
      <section class="offer-img d-flex justify-content-center">
        <%= cl_image_tag @offer.photos.first.key, height: 100, width: 150, crop: :fill, alt: "#{@offer.title} photo" %>
          <% if @offer.photos.count == 0 %>
            <%= image_tag "", height: 100, width: 150, crop: :fill, alt: "No photo" %>
          <% end %>
      </section>
      <div class="offer-info d-flex flex-column justify-content-center">
        <h3><%= @offer.title %></h3>
        <p><%= @offer.description%></p>
      </div>
    </section>
    <div class="price-title">
      <h3>Détails du prix</h3>
    <div class="booking-info-bottom d-flex flex-row justify-content-between">
      <section id="price-recap-left">
        <div class="price-summary mb-5">
          <p><%= @offer.price %>€ x 1 jour</p>
          <p>Frais de service (2%)</p>
        </div>
        <div class="price-total">
          <p><strong>Total</strong></p>
        </div>
      </section>
        <section id="price-recap-right">
          <div class="price-summary mb-5">
            <% frais = (@offer.price*0.02).round(2)  %>
            <p><%= @offer.price %>€</p>
            <p><%= frais%>€</p>
          </div>
          <div class="price-total">
            <p><strong><%= (@offer.price + frais).round(2) %>€</strong></p>
          </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</div>
<%= render "footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateFaker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/offers/_carousel.html.erb
<div class="slider">
  <div class="slide-track">
    <% @offers.each do |offer| %>
      <% if offer.photos.any? %> <!-- Ensure the offer has photos -->
        <%= link_to offer_path(offer), class: 'slide text-decoration-none' do %>
          <div class="text-center" style="color: #30207C; font-family: Arial, sans-serif; font-size: 22px;">
            <%= offer.title %>
          </div>
          <div class="carousel__face" style="background-image: url('<%= offer.photos.first.url %>');">
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-offer">
    <% if !user_signed_in? %>
      <%= link_to(new_user_session_path) do %>
        <i class="fa-regular fa-user avatar"></i>
      <% end %>
    <% elsif current_user.photo.key.nil? %>
      <%= link_to(user_path(current_user)) do%>
        <i class="fa-regular fa-user avatar"></i>
      <% end %>
    <% else %>
      <%= link_to(user_path(current_user)) do%>
        <%= cl_image_tag current_user.photo.key, crop: :fill, alt: "user avatar", class: "avatar" %>
      <% end %>
    <% end %>

    <% if user_signed_in? %>
      <div class="navbar-offer">
        <%= button_to destroy_user_session_path, method: :delete do %>
          <i class="fa-solid fa-right-from-bracket"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= link_to(root_path) do %>
    <div class="navbar-logo" style="display: flex; align-items: center;">
      <%= image_tag "logo", alt: "logo", style: "margin-right: 10px;" %>
      <div class="text-logo">
        <p style="margin: 0">Date Faker</p>
      </div>
    </div>
  <% end %>

  <div class="navbar-offers">
    <div class="navbar-offer">
      <%= link_to "Je dépose une offre", new_offer_path, class: "offer-btn underline-p"%>
    </div>
    <div class="navbar-offer">
      <%= link_to "Mes réservations", bookings_path, class: "offer-btn underline-p"%>
    </div>
  </div>
</nav>

app/views/offers/index.html.erb
<%= render "navbar" %>

    <section class="real-connections-section">
    <div class="text-content-index">
      <h1 class="index-title"><span data-controller="typed" data-typed-strings-value="<%= ["Trouvez votre <span class='highlight'>fake date </span>pour tous les évènements en 1 clic"] %>" class="index-title">
      </span></h1>
      <p class="description"> Vous craignez les questions gênantes en famille ou de venir seul à un mariage, dîner d'affaires, ou autre?<br> Pas de souci ! Avec DateFaker, évitez l'embarras grâce à un compagnon fictif, quelle que soit l'occasion.</p>
    </div>
    <div class="image-content">
      <%= image_tag "img2", alt: "img_2", width: "auto", height: "300" %>
      <div class="heart-icon">
        <img src="path-to-your-image/heart-icon.png" alt="">
      </div>
    </div>
  </section>

<section class="category">
    <h2 class="title">Trouvez le complice pour chaque occasion</h2>
  <div class="cards-collection">
      <div class="boxes">
        <div class="box">
        <%= image_tag "mariage", alt: "mariage", width: "auto", height: "120" %>
          <p class="text-center" mt-4 style="color: #30207C; font-family: Arial, sans-serif; font-size: 16px;">Mariage</p>
    </div>
      <div class="box">
        <%= image_tag "meal", alt: "meal", width: "auto", height: "120" %>
          <p class="text-center" style="color: #30207C; font-family: Arial, sans-serif; font-size: 16px;">Repas de famille</p>
      </div>
        <div class="box">
          <%= image_tag "business", alt: "business", width: "auto", height: "120" %>
            <p class="text-center" style="color: #30207C; font-family: Arial, sans-serif; font-size: 16px;">Dîner d'affaires</p>
      </div>
        <div class="box">
          <%= image_tag "hug", alt: "hug", width: "auto", height: "120" %>
            <p class="text-center" style="color: #30207C; font-family: Arial, sans-serif; font-size: 16px;">Consolation après une rupture</p>
        </div>
          <div class="box">
            <%= image_tag "sad", alt: "sad", width: "auto", height: "120" %>
              <p class="text-center" style="color: #30207C; font-family: Arial, sans-serif; font-size: 16px;">Support lors d'une situation stressante</p>
        </div>
          <div class="box">
            <%= image_tag "interrogation", alt: "interrogation", width: "auto", height: "120" %>
              <p class="text-center" style="color: #30207C; font-family: Arial, sans-serif; font-size: 16px;">Autres</p>
          </div>
        </div>
  </div>
</section>

<section class="offers" style="background-color: #b3c6f1">
  <div class="offers-category d-flex flex-column">
    <h2 class="second-title">Découvrez Nos Experts : Prêts à rendre votre moment inoubliable !</h2>
      <%= render 'carousel' %>
  </div>
</section>

  <section class="testimonial-section">
    <div class="testimonial-content">
      <h2>Ce que pense <span class="highlight">nos utilisateurs</span></h2>
      <p class="testimonial-quote"><em> "J’ai utilisé DateFaker pour un mariage où je ne voulais pas aller seul, et c’était parfait ! Mon 'faux' compagnon était charmant et a su jouer son rôle à la perfection. Aucune question gênante, et j’ai passé une super soirée sans le moindre stress. Je recommande vivement 🥰"</em></p>
      <p class="testimonial-author">Helena Ann</p>
    </div>

    <div class="image-container">
      <%= image_tag "mobile", alt: "mobile", width: "auto", height: "240" %>
    </div>
  </section>

  <section class="app-works-section work_section">
    <div class="content-container">
      <h1 class="index-title">Comment ça <span class="highlight">marche?</span></h1>
        <p class="description"> DateFaker s'engage à vous aider dans les situations sociales délicates en vous connectant avec des experts prêts à jouer le rôle parfait pour vous.      </p>

      <div class="steps-container">
        <div class="step-box">
          <div class="step-number">1</div>
            <h2 class="index-box-item">Inscrivez-vous</h2>
        </div>
          <div class="step-box">
            <div class="step-number">2</div>
              <h2 class="index-box-item">Lancer la recherche</h2>
        </div>
          <div class="step-box">
            <div class="step-number">3</div>
              <h2 class="index-box-item">Postuler un offre</h2>
        </div>
          <div class="step-box">
            <div class="step-number">4</div>
            <h2 class="index-box-item">Réserver votre date</h2>
        </div>
      </div>
    </div>

    <div class="image-container image-index">
      <%= image_tag "service", alt: "service", width: "auto", height: "330" %>
    </div>
  </section>

<%= render "footer" %>

app/views/offers/new.html.erb
<%= render 'navbar' %>
<h1>Créez votre offre</h1>
<div class="form-container" id="offers-form">
  <%= simple_form_for @offer do |f| %>
    <div class="form-inputs", style="background-color: #fff; margin: 20px auto;
      width: 100%; padding: 30px; box-sizing: border-box; border-radius: 10px;">
      <%= f.input :title, label: "Titre de l'annonce :", autofocus: true%>
      <%= f.input :description, label: 'Décris ton annonce', autofocus: true %>
      <%= f.input :price, label: 'Quel est ton prix par jour ?', autofocus: true %>
      <%= f.input :photos, as: :file, input_html: { multiple: true }, label: 'Ajoute tes plus belles photos !' %>
      <%= f.input :localisation, label: 'Dans quelle ville/région ?',
        input_html: {data: {localisation_autocomplete_target: "localisation"}, class: "d-none"},
        wrapper_html: {data: {controller: "localisation-autocomplete", localisation_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
      %>
      <%= f.submit "Envoyer", class: "button" %>
    </div>
  <% end %>
</div>
<%= render "footer" %>

app/views/offers/show.html.erb
<%= render "navbar" %>
<main>
  <h1 style="text-align: start; margin-left: 2.5em"><strong><%= @offer.title %></strong></h1>
  <div class="card">
    <div class="profile">
      <div class="photo-gallery">
        <div class="profile-image main-image" style="background-image: url('<%= @offer.photos.first.url %>'); border-radius: 5px">
        </div>
        <div class="secondary-images">
          <% @offer.photos.each do |photo| %>
            <% if photo != @offer.photos.first %>
              <div class="secondary-image" style="background-image: url('<%= photo.url %>')">
              <%# #donne le lien de la photo %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <section class="details" style="border-radius: 5px; background-color: #ffffff">
      <div class="location">
        <div style="margin-right:24px">
          <% if !@user.photo.key.nil? %>
            <%= cl_image_tag @user.photo.key, crop: :fill, alt: "#{@user.first_name} photo", class: "avatar" %>
          <% else %>
            <h4 class="avatar-round"><%= @user.first_name.chars[0] %><%= @user.last_name.chars[0] %> </h4>
          <% end %>
        </div>
        <div class="user-details">
          <p> <strong>Nom:</strong> <%= @user.first_name %> <%= @user.last_name %></p>
          <p> <strong>Age:</strong> <%= @user.age %></p>
          <p> <strong>Genre:</strong> <%= @user.gender %></p>
          <p> <strong>Prix:</strong> <%= @offer.price %> €</p>
          <p> <strong>Description:</strong> <%= @offer.description %></p>
          <p> <strong>Localisation:</strong> <%= @offer.localisation %></p>
        </div>
      </div>
      <% if current_user != @user %>
        <%= link_to "Réserver", new_offer_booking_path(@offer), class: "btn"%>
      <% end %>
    </section>
  </div>
</main>
<%= render "footer" %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_footer.html.erb
<div class="footer-dark">
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-3 item">
          <%= image_tag "logo", alt: "logo_date_faker", width: "auto", height: "120" %>
        </div>
        <div class="col-sm-6 col-md-3 item">
          <ul>
            <a href="#"><h3>A propos</h3></a>
            <a href="#"><h3>Réserver un fake date</h3></a>
            <a href="#"><h3>Offrir un service</h3></a>
            <a href="#"><h3>Carrière</h3></a>
          </ul>
        </div>
        <div class="col-md-6 item text">
            <h3>Date Faker</h3>
            <p>Amour sans détour! <br> Trouve ton fake date pour tous les évènements en 1 clic</p>
        </div>
        <div class="col item social">
          <a href="#"><i class="fa-brands fa-facebook fa-xl icon ion-social-facebook"></i></a>
          <a href="#"><i class="icon ion-social-twitter fa-brands fa-instagram fa-xl"></i></a>
          <a href="#"><i class="icon ion-social-snapchat fa-brands fa-github fa-xl"></i></a>
          <a href="#"><i class="icon ion-social-instagram fa-solid fa-poo fa-xl"></i></a>
        </div>
      </div>
    </div>
    <p class="copyright">Date Faker © 2024</p>
  </footer>
</div>

app/views/users/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-offer">
    <% if !user_signed_in? %>
      <%= link_to(new_user_session_path) do %>
        <i class="fa-regular fa-user avatar"></i>
      <% end %>
    <% elsif current_user.photo.key.nil? %>
      <%= link_to(user_path(current_user)) do%>
        <i class="fa-regular fa-user avatar"></i>
      <% end %>
    <% else %>
      <%= link_to(user_path(current_user)) do%>
        <%= cl_image_tag current_user.photo.key, crop: :fill, alt: "user avatar", class: "avatar" %>
      <% end %>
    <% end %>

    <% if user_signed_in? %>
      <div class="navbar-offer">
        <%= button_to destroy_user_session_path, method: :delete do %>
          <i class="fa-solid fa-right-from-bracket"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= link_to(root_path) do %>
    <div class="navbar-logo" style="display: flex; align-items: center;">
      <%= image_tag "logo", alt: "logo", style: "margin-right: 10px;" %>
      <div class="text-logo">
        <p style="margin: 0">Date Faker</p>
      </div>
    </div>
  <% end %>

  <div class="navbar-offers">
    <div class="navbar-offer">
      <%= link_to "Je dépose une offre", new_offer_path, class: "offer-btn"%>
    </div>
    <div class="navbar-offer">
      <%= link_to "Mes réservations", bookings_path, class: "offer-btn"%>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<%= render "navbar" %>

<div class="card" style="background-color: #fff; border-radius: 15px; box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1); margin: 20px auto; padding: 20px; max-width: 90%;">
  <h2 class="mb-3 p-3" style="font-size: 28px; color: #30207c; text-align: left;">Offres publiées</h2>

  <% if @user.offers.empty? %>
    <div style="text-align: center; padding: 20px; color: #555;">
      <h3>Woah c'est vide!</h3>
    </div>
  <% else %>
    <div class="cards-offers d-flex flex-wrap gap-4" style="justify-content: flex-start;">
      <% @user.offers.each do |offer| %>
        <div class="card-date-offer" style="position: relative; background-color: #f8f8f8; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05); padding: 15px 15px 60px 15px; max-width: 350px; text-align: center;">
          <div style="margin-bottom: 15px;">
            <%= link_to offer_path(offer) do %>
              <%= cl_image_tag offer.photos.first.key, height: 200, width: 300, gravity: :auto, crop: :fill, alt: "#{offer.title} photo", style: "border-radius: 10px;" %>
            <% end %>
          </div>
          <div class="offer-details" style="padding: 10px;">
            <h3 style="font-size: 22px; color: #30207c; margin-bottom: 10px;"><%= offer.title %></h3>
            <p style="color: #555;"><%= offer.description %></p>
              <%= link_to "Supprimer", offer_path(offer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-btn", style: "background-color: #ff4d4d; color: white; padding: 10px 20px; border: none; border-radius: 5px; text-decoration: none; font-weight: bold;" %>
          </div>

        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= render "footer" %>